Repository mohitahlawat2001/MathematicsSwitchApp, pull requests merged in 2023-10, with the labels that each got.

#26 Fixed the bug
  index.js
Labels: hacktoberfest, hacktoberfest-accepted

#28 BUG FIXED
  index.html
  index.js
Labels: bug, hacktoberfest

#30 Features added
  index.html
  index.js
Labels: documentation, hacktoberfest, hacktoberfest-accepted
